from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
from datetime import datetime
import random

from database import Base, engine, SessionLocal
from models import Layout, Component


# ── FastAPI APP ──────────────────────────────────────────────────────────────────
app = FastAPI()

# --- CORS so CRA (localhost:3000) can talk to FastAPI (localhost:8000)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── DB SCHEMA CREATION ──────────────────────────────────────────────────────────
Base.metadata.create_all(bind=engine)


# ── Pydantic input models ───────────────────────────────────────────────────────
class ComponentIn(BaseModel):
    position: int
    type: str
    config: dict


class LayoutIn(BaseModel):
    name: str
    components: List[ComponentIn]


# ── Seed demo report once on startup ────────────────────────────────────────────
@app.on_event("startup")
def seed_data() -> None:
    with SessionLocal() as db:
        if db.query(Layout).filter_by(name="demo-report").first():
            return

        demo = Layout(name="demo-report")
        demo.components.append(
            Component(
                position=0,
                type="text",
                config={"data": "Hello from your first text block!"},
            )
        )
        db.add(demo)
        db.commit()


# ── ROUTES ──────────────────────────────────────────────────────────────────────
@app.get("/layouts")
def list_layouts():
    with SessionLocal() as db:
        names = db.query(Layout.name).all()
        return [name for (name,) in names]


@app.get("/layouts/{name}")
def get_layout(name: str):
    with SessionLocal() as db:
        layout = db.query(Layout).filter_by(name=name).first()
        if not layout:
            raise HTTPException(status_code=404, detail="Layout not found")

        return {
            "name": layout.name,
            "created_at": layout.created_at.isoformat(),
            "components": sorted(
                [
                    {"type": c.type, "position": c.position, "config": c.config}
                    for c in layout.components
                ],
                key=lambda x: x["position"],
            ),
        }


@app.post("/layouts/")
def create_or_update_layout(layout_in: LayoutIn):
    with SessionLocal() as db:
        layout = db.query(Layout).filter_by(name=layout_in.name).first()

        if layout:
            # If it exists, clear old components and update in place
            db.query(Component).filter_by(layout_id=layout.id).delete()
        else:
            # If new, create it
            layout = Layout(name=layout_in.name)
            db.add(layout)
            db.flush()  # to get layout.id

        for comp in layout_in.components:
            db.add(
                Component(
                    layout_id=layout.id,
                    position=comp.position,
                    type=comp.type,
                    config=comp.config,
                )
            )

        db.commit()
        return {"status": "created_or_updated", "name": layout.name}


@app.put("/layouts/{name}")
def update_layout(name: str, layout_in: LayoutIn):
    with SessionLocal() as db:
        layout = db.query(Layout).filter_by(name=name).first()
        if not layout:
            raise HTTPException(status_code=404, detail="Layout not found")

        db.query(Component).filter_by(layout_id=layout.id).delete()

        for comp in layout_in.components:
            db.add(
                Component(
                    layout_id=layout.id,
                    position=comp.position,
                    type=comp.type,
                    config=comp.config,
                )
            )

        db.commit()
        return {"status": "updated", "name": layout.name}


@app.delete("/layouts/{name}")
def delete_layout(name: str):
    with SessionLocal() as db:
        layout = db.query(Layout).filter_by(name=name).first()
        if not layout:
            raise HTTPException(status_code=404, detail="Layout not found")
        db.delete(layout)
        db.commit()
        return {"status": "deleted"}


@app.get("/sample-layout")
def sample_layout():
    layout = {
        "name": f"sample-{random.randint(1000, 9999)}",
        "components": [
            {
                "type": "text",
                "position": 0,
                "config": {
                    "data": "This is a sample text block generated by the backend."
                },
            },
            {
                "type": "image",
                "position": 1,
                "config": {"data": "https://via.placeholder.com/300x100"},
            },
            {
                "type": "table",
                "position": 2,
                "config": {
                    "headers": ["Name", "Role"],
                    "rows": [["Alice", "Engineer"], ["Bob", "Designer"]],
                },
            },
            {
                "type": "graph",
                "position": 3,
                "config": {
                    "type": "bar",
                    "data": [
                        {"label": "Jan", "value": random.randint(10, 100)},
                        {"label": "Feb", "value": random.randint(10, 100)},
                        {"label": "Mar", "value": random.randint(10, 100)},
                    ],
                },
            },
        ],
    }
    return layout
